notifications:
  webhooks:
    - http://rcmp.tenthbit.net
    - http://rcmp.tenthbit.net/irc.freenode.net/sicuro
  
  email:
    on_success: change # default: change
    on_failure: change # default: always

language: ruby
rvm:
  - 2.1.0
  - jruby-19mode
  - rbx-2
  - ruby-head
  - jruby-head

